### ISSUE TITLE
Rake File issue

### ISSUE THREAD

**Issue by payalthummar** [skoenen/ci_2.04_programming#2]
Hello Pro. Koenen,

I am trying to do every step which you told. But when I try to write 
**$ sudo rake** after installing every file, It gives an error like...

rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)

what should I do???

Thanks in advance

**Comment by skoenen** [comment]
Hello,please file an issue. Kind regards, Stefan Koenen Am 07.05.2019 10:11 schrieb payalthummar <notifications@github.com>:Hello Pro. Koenen,
I am trying to do every step which you told. But when I try to write
$ sudo rake after installing every file, It gives an error like...
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/var/lib/gems/2.5.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
what should I do???
Thanks in advance

**Comment by jfamousket** [comment]
So your terminal should point to the directory (folder) where you downloaded the repository to, because the rake file is within that directory. To give you any meaningful help I need to know the CLI and OS you are working with because doing this would vary based on these factors.

**Comment by skoenen** [comment]
- Closing
- No Rake needed with Commit 0520a6e9950133c727f1b786e0849656a1a4d298
- Have look at new instructions.
