### ISSUE TITLE
you don't have /root/.gem/ruby/2.6.0/bin in your PATH

### ISSUE THREAD

**Issue by ahmed711** [skoenen/ci_2.04_programming#4]
hi guys 
so i'm trying to install bundler after i installed ruby but it's not working every time i try 
i get this error 
![image](https://user-images.githubusercontent.com/15662374/57440636-a7352300-7248-11e9-9bc4-e3b45eb8efe3.png)

i tried all instructions but i think it's something about the path that is not working

**Comment by skoenen** [comment]
This is a warning and means that the path `/root/.gem/ruby/2.6.0/bin` is in the Environment variable where the system searches for executables.

In the readme it is explained how to fix this: [Readme](https://github.com/skoenen/ci_2.04_programming#make-sure-that-installed-binaries-of-gems-are-usable)

after that you either 
- log out and log in
- or use `$ source ~/.profile`

Or in your specific case (_because you are root user_)
`# source /root/.profile`

After that you can check with

`$ env | grep -i path`

and should get a response similiar to:

`/root/.gem/ruby/2.6.0/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by skoenen** [comment]
No follow up question -> Closing
